[package]
name = "sqlite_parser"
version = "0.1.0"
authors = ["Jasper <Jasperav@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]