name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all -- -D warnings